[package]
name = "an2linuxserver"
version = "0.1.0"
authors = ["rusty <rusty@spoqa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
configparser = "2.0.0"
dirs = "3.0.1"
regex = "1.4.3"
rustls = { version = "0.19.0", features = ["dangerous_configuration"] }
rustls-pemfile = "0.2.0"
ring = "0.16.20"
structopt = "0.3.21"
base64 = "0.13.0"
webpki = "0.21.4"
x509-signature = "0.5.0"
