[package]
name = "an2linuxserver"
version = "0.1.0"
authors = ["rusty <rusty@spoqa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
configparser = "2.0.0"
dirs = "3.0.1"
regex = "1.4.3"
rustls = "0.19.0"
rustls-pemfile = "0.2.0"
ring = "0.16.20"
structopt = "0.3.21"
